### ISSUE TITLE
Adding an exporter without labels crashes

### ISSUE THREAD

**Issue by cburki** [camptocamp/prometheus-puppetdb#27]
When you add an exporter without specified labels, prometheus-puppetdb crashes.
```
panic: interface conversion: interface {} is nil, not map[string]interface {}
goroutine 1 [running]:
main.extractTargets(0xe8ea00, 0xc4201bf760, 0xc42009fd40, 0x4, 0xc420389e08, 0x0, 0x0)
        /home/ldepriester/go/src/github.com/camptocamp/prometheus-puppetdb/main.go:196 +0x7a5
main.getTargets(0xc42034ef40, 0xf36d53, 0x13, 0x0, 0x0)
        /home/ldepriester/go/src/github.com/camptocamp/prometheus-puppetdb/main.go:126 +0x882
main.main()
/home/ldepriester/go/src/github.com/camptocamp/prometheus-puppetdb/main.go:329 +0x43d
```
Here is a sample of an exporter which trigger the crash. It does not have any labels definition.
```
kafka:
  - url: http://128.178.166.17:7071/metrics
```
And we need to be able to declare exporter whithout labels.

**Comment by mcanevet** [comment]
we have to add a check before this line : https://github.com/camptocamp/prometheus-puppetdb/blob/master/main.go#L196
